import { StyleSheet } from 'react-native';

export const createThemeStyles = (theme, progressPercentage) => ({
  appShell: [styles.appShell, { backgroundColor: theme.background }],
  containerBackground: { backgroundColor: theme.background },
  modePill: { backgroundColor: theme.pill },
  modePillText: { color: theme.accent },
  progressBar: {
    width: `${Math.min(progressPercentage, 100)}%`,
    backgroundColor: theme.pill,
  },
});

export const createSwatchStyle = (color) => ({
  backgroundColor: color,
});

export const createWeekBarStyle = (
  daySeconds,
  maxWeekDaySeconds
) => ({
  height: `${Math.max(
    (daySeconds / maxWeekDaySeconds) * 100,
    daySeconds > 0 ? 12 : 4
  )}%`,
});

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 36,
  },
  webContainer: {
    alignItems: 'flex-start',
    paddingLeft: 72,
    paddingRight: 430,
    paddingVertical: 46,
  },
  webCompactContainer: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 34,
    paddingVertical: 44,
  },
  focusContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 24,
    paddingRight: 24,
    paddingVertical: 36,
  },
  header: {
    width: '100%',
    maxWidth: 460,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  webHeader: {
    maxWidth: 720,
    marginBottom: 22,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appName: {
    color: 'rgba(255, 255, 255, 0.88)',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 2,
  },
  modePill: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  modePillText: {
    fontSize: 13,
    fontWeight: '800',
  },
  menuButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 12,
    marginLeft: 8,
  },
  menuButtonText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 24,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  description: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 16,
    marginBottom: 28,
    textAlign: 'center',
  },
  timerCard: {
    width: '100%',
    maxWidth: 460,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderColor: 'rgba(255, 255, 255, 0.24)',
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 24,
    paddingVertical: 28,
    marginBottom: 16,
  },
  webMainCard: {
    maxWidth: 720,
    paddingHorizontal: 42,
    paddingVertical: 40,
    shadowColor: '#020817',
    shadowOpacity: 0.22,
    shadowRadius: 26,
    shadowOffset: {
      width: 0,
      height: 18,
    },
  },
  timer: {
    color: '#FFFFFF',
    fontSize: 72,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  activeProjectBadge: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 18,
  },
  activeProjectLabel: {
    color: 'rgba(255, 255, 255, 0.72)',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  activeProjectName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 3,
    textAlign: 'center',
  },
  progressBackground: {
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.20)',
    borderRadius: 4,
    marginTop: 20,
    marginBottom: 16,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: 4,
  },
  statusText: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 14,
    textAlign: 'center',
  },
  reminderBanner: {
    backgroundColor: 'rgba(255, 227, 166, 0.16)',
    borderColor: 'rgba(255, 227, 166, 0.44)',
    borderWidth: 1,
    borderRadius: 14,
    marginTop: 18,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  reminderTitle: {
    color: '#FFE3A6',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  reminderText: {
    color: 'rgba(255, 255, 255, 0.86)',
    fontSize: 14,
    marginTop: 4,
    textAlign: 'center',
  },
  reminderActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 14,
  },
  reminderPrimaryButton: {
    backgroundColor: '#FFE3A6',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginRight: 8,
  },
  reminderPrimaryButtonText: {
    color: '#101D3A',
    fontSize: 13,
    fontWeight: '800',
  },
  reminderSecondaryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    borderColor: 'rgba(255, 255, 255, 0.28)',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  reminderSecondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  buttonContainer: {
    width: '100%',
    maxWidth: 460,
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
  },
  webButtonContainer: {
    maxWidth: 720,
    justifyContent: 'center',
  },
  button: {
    minWidth: 125,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    paddingHorizontal: 24,
    paddingVertical: 15,
    borderRadius: 12,
    marginHorizontal: 6,
    alignItems: 'center',
  },
  mainButton: {
    backgroundColor: 'rgba(230, 180, 80, 0.34)',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  confirmOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(2, 8, 23, 0.58)',
    padding: 24,
  },
  confirmDialog: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#F7FAFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    elevation: 16,
  },
  confirmTitle: {
    color: '#101D3A',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  confirmMessage: {
    color: '#637089',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 10,
    textAlign: 'center',
  },
  confirmActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 18,
  },
  confirmCancelButton: {
    backgroundColor: '#E8EEF8',
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
    marginRight: 10,
  },
  confirmCancelText: {
    color: '#101D3A',
    fontSize: 14,
    fontWeight: '800',
  },
  confirmDangerButton: {
    backgroundColor: '#101D3A',
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  confirmDangerText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  modeButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 18,
  },
  modeButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  settingsCard: {
    width: '100%',
    maxWidth: 460,
    backgroundColor: 'rgba(247, 250, 255, 0.95)',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
  },
  webSettingsCard: {
    maxWidth: 720,
  },
  settingsTitle: {
    color: '#101D3A',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 14,
  },
  settingsLabel: {
    color: '#101D3A',
    fontSize: 14,
    fontWeight: '800',
  },
  durationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  durationLabel: {
    color: '#101D3A',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
  },
  durationControl: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8EEF8',
    borderRadius: 12,
    paddingHorizontal: 6,
    paddingVertical: 5,
  },
  stepButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepButtonText: {
    color: '#101D3A',
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 24,
  },
  durationInput: {
    width: 48,
    color: '#101D3A',
    fontSize: 18,
    fontWeight: '800',
    marginHorizontal: 4,
    paddingVertical: 6,
    textAlign: 'center',
  },
  durationUnit: {
    width: 28,
    color: '#637089',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 10,
  },
  sessionTitleInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D6DFEF',
    borderWidth: 1,
    borderRadius: 12,
    color: '#101D3A',
    fontSize: 15,
    fontWeight: '800',
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  sessionTypeOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  sessionTypeButton: {
    backgroundColor: '#E8EEF8',
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  selectedSessionTypeButton: {
    backgroundColor: '#101D3A',
    borderColor: '#101D3A',
  },
  sessionTypeButtonText: {
    color: '#637089',
    fontSize: 12,
    fontWeight: '800',
  },
  selectedSessionTypeButtonText: {
    color: '#FFFFFF',
  },
  themeSelector: {
    marginTop: 0,
  },
  themeToggleButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE4F2',
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  themeToggleText: {
    color: '#101D3A',
    fontSize: 13,
    fontWeight: '800',
  },
  themeToggleIcon: {
    color: '#101D3A',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 20,
  },
  themeOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  themeOption: {
    alignItems: 'center',
    backgroundColor: '#E8EEF8',
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  selectedThemeOption: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E6B450',
  },
  themeSwatches: {
    flexDirection: 'row',
    marginBottom: 7,
  },
  themeSwatch: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginHorizontal: 2,
  },
  themeOptionText: {
    color: '#637089',
    fontSize: 12,
    fontWeight: '800',
  },
  selectedThemeOptionText: {
    color: '#101D3A',
  },
  menuThemeCard: {
    backgroundColor: '#E8EEF8',
    borderRadius: 16,
    padding: 10,
    marginTop: 14,
  },
  soundRow: {
    borderTopColor: '#DDE5F1',
    borderTopWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingTop: 14,
  },
  soundHint: {
    color: '#637089',
    fontSize: 12,
    marginTop: 4,
    maxWidth: 220,
  },
  soundToggle: {
    backgroundColor: '#E8EEF8',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginLeft: 12,
  },
  soundToggleActive: {
    backgroundColor: '#101D3A',
  },
  soundToggleText: {
    color: '#637089',
    fontSize: 12,
    fontWeight: '800',
  },
  soundToggleTextActive: {
    color: '#FFFFFF',
  },
  sessionCard: {
    width: '100%',
    maxWidth: 460,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.13)',
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  webSessionCard: {
    maxWidth: 720,
  },
  sessionTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  sessionSubtitle: {
    color: 'rgba(255, 255, 255, 0.76)',
    fontSize: 12,
    marginTop: 3,
  },
  sessionCount: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  resetAllText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 13,
    marginTop: 16,
    textDecorationLine: 'underline',
  },
  historyPanel: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 320,
    maxWidth: '88%',
    backgroundColor: '#F7FAFF',
    paddingHorizontal: 18,
    paddingTop: 42,
    paddingBottom: 18,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: {
      width: -4,
      height: 0,
    },
    elevation: 12,
  },
  desktopHistoryPanel: {
    top: 24,
    right: 24,
    bottom: 24,
    width: 372,
    maxWidth: 372,
    borderRadius: 20,
    paddingTop: 24,
    shadowOpacity: 0.18,
  },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  historyTitle: {
    color: '#101D3A',
    fontSize: 20,
    fontWeight: '800',
  },
  historySubtitle: {
    color: '#637089',
    fontSize: 13,
    marginTop: 4,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#E8EEF8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: '#101D3A',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 26,
  },
  statsCard: {
    backgroundColor: '#E8EEF8',
    borderRadius: 16,
    padding: 10,
    marginBottom: 14,
  },
  statsToggleButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE4F2',
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  statsToggleText: {
    color: '#101D3A',
    fontSize: 13,
    fontWeight: '800',
  },
  statsToggleMeta: {
    color: '#637089',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  statsToggleIcon: {
    color: '#101D3A',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 20,
  },
  statsGrid: {
    flexDirection: 'row',
    marginTop: 10,
  },
  statBox: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 10,
    marginRight: 6,
  },
  statLabel: {
    color: '#637089',
    fontSize: 11,
    fontWeight: '800',
  },
  statValue: {
    color: '#101D3A',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 5,
  },
  statMeta: {
    color: '#637089',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  weekChart: {
    height: 96,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 8,
  },
  weekChartItem: {
    flex: 1,
    alignItems: 'center',
  },
  weekBarTrack: {
    width: 18,
    height: 56,
    borderRadius: 9,
    backgroundColor: '#E8EEF8',
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  weekBar: {
    width: '100%',
    backgroundColor: '#E6B450',
    borderRadius: 9,
  },
  weekChartLabel: {
    color: '#637089',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 6,
  },
  newProjectCard: {
    backgroundColor: '#E8EEF8',
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  newProjectTitle: {
    color: '#101D3A',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 10,
  },
  projectInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D6DFEF',
    borderWidth: 1,
    borderRadius: 12,
    color: '#101D3A',
    fontSize: 15,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 10,
  },
  createProjectButton: {
    backgroundColor: '#101D3A',
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 12,
  },
  createProjectButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  historyList: {
    flex: 1,
  },
  projectCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE4F2',
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  activeProjectCard: {
    borderColor: '#E6B450',
    backgroundColor: '#FFF7E4',
  },
  projectHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  projectTitleGroup: {
    flex: 1,
    paddingRight: 10,
  },
  projectName: {
    color: '#101D3A',
    fontSize: 17,
    fontWeight: '800',
  },
  projectMeta: {
    color: '#637089',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  selectProjectButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  selectedProjectButton: {
    backgroundColor: '#E6B450',
  },
  selectProjectButtonText: {
    color: '#101D3A',
    fontSize: 13,
    fontWeight: '800',
  },
  selectedProjectButtonText: {
    color: '#FFFFFF',
  },
  emptyProjectText: {
    color: '#637089',
    fontSize: 13,
    lineHeight: 18,
  },
  historyToggleButton: {
    backgroundColor: '#F3F6FB',
    borderColor: '#DCE4F2',
    borderWidth: 1,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  historyToggleText: {
    color: '#101D3A',
    fontSize: 12,
    fontWeight: '800',
  },
  historyToggleIcon: {
    color: '#101D3A',
    fontSize: 17,
    fontWeight: '900',
    lineHeight: 19,
  },
  historyItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  partBadge: {
    minWidth: 58,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#101D3A',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginRight: 10,
  },
  partBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  historyItemContent: {
    flex: 1,
  },
  topicInput: {
    backgroundColor: '#F3F6FB',
    borderColor: '#DCE4F2',
    borderWidth: 1,
    borderRadius: 10,
    color: '#101D3A',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  historyDate: {
    color: '#637089',
    fontSize: 12,
    fontWeight: '700',
  },
  historyType: {
    color: '#637089',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  historyMinutes: {
    color: '#101D3A',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 5,
  },
  deleteHistoryButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFE8E8',
    borderRadius: 10,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  deleteHistoryButtonText: {
    color: '#A33A3A',
    fontSize: 12,
    fontWeight: '800',
  },
});
